# Generated by Django 4.2.1 on 2023-07-07 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_package_service_sessions_profile_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="package",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="accounts.package",
            ),
        ),
    ]
