# Generated by Django 4.2.1 on 2023-06-15 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.trainers'),
        ),
    ]
