# Generated by Django 4.2.1 on 2023-07-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="package_name",
            field=models.CharField(default=None, max_length=255),
        ),
    ]
