# Generated by Django 4.2.1 on 2023-07-12 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_package_package_name"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Service",
        ),
    ]
