# Generated by Django 4.2.1 on 2023-06-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessions',
            options={'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.RenameField(
            model_name='sessions',
            old_name='name',
            new_name='session_name',
        ),
        migrations.AlterModelTable(
            name='sessions',
            table='sessions',
        ),
    ]
