# Generated by Django 4.2.1 on 2023-07-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_delete_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_no",
            field=models.CharField(max_length=12),
        ),
    ]
