# Generated by Django 4.2.1 on 2023-05-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_transaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recipient_no',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender_no',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
