# Generated by Django 4.2.1 on 2023-06-16 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_sessions_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='recipient_no',
        ),
    ]
