# Generated by Django 4.2.1 on 2023-07-12 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_profile_phone_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trainers",
            name="last_name",
        ),
    ]
