# Generated by Django 4.2.1 on 2023-06-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_transaction_recipient_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='package',
            field=models.CharField(max_length=255),
        ),
    ]
