# Generated by Django 4.2.1 on 2023-06-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_transaction_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start',
            field=models.CharField(max_length=20),
        ),
    ]
