# Generated by Django 4.2.1 on 2023-06-13 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_trainer_rename_events_event_trainers_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Events',
        ),
        migrations.RemoveField(
            model_name='trainers',
            name='id',
        ),
        migrations.AlterField(
            model_name='trainers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
