# Generated by Django 4.2.1 on 2023-06-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_event_events_remove_trainers_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Events', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='trainers',
            options={'verbose_name': 'Trainers', 'verbose_name_plural': 'Trainers'},
        ),
        migrations.AlterModelTable(
            name='trainers',
            table='trainers',
        ),
    ]
