# Generated by Django 4.2.1 on 2023-06-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_id_booking_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_photo',
            field=models.ImageField(blank=True, upload_to='users/%Y/%m/%d/'),
        ),
    ]
