# Generated by Django 4.2.1 on 2023-06-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_package_package_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_photo',
            field=models.ImageField(blank=True, upload_to='site/%Y/%m/%d/'),
        ),
    ]
