# Generated by Django 4.2.1 on 2023-06-30 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_alter_profile_sex"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="address",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
